### ISSUE TITLE
Support for database and schema needed

### ISSUE THREAD

**Issue by skunkworksguy** [sfc-gh-bhess/st_snowauth#1]
First of all, thank you for an amazing package on this. Great work.

I'm having a need for database and schema support for the session. At the very least, if this is difficult to implement, the PUBLIC schema could be hardcoded into snow_configs at line 94 in st_snowauth.py, just to give the connection something to work with.

**Comment by sfc-gh-bhess** [comment]
I created a v1.1 that allows you to specify `connection` parameters to the `config`. 
The `connection` field of the `config` dictionary is itself a dictionary. The keys/values in that dictionary are added as-is to the dictionary that is used to make the Snowpark Session.

**Comment by skunkworksguy** [comment]
Fantastic. Thank you!
